# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserMainWindow(object):
    def setupUi(self, UserMainWindow):
        UserMainWindow.setObjectName("UserMainWindow")
        UserMainWindow.resize(1052, 802)
        UserMainWindow.setMinimumSize(QtCore.QSize(500, 500))
        UserMainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserMainWindow.setWindowIcon(icon)
        UserMainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(UserMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Game_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Game_Area.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.Game_Area.setWidgetResizable(True)
        self.Game_Area.setObjectName("Game_Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1028, 384))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gameBotton_2 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.gameBotton_2.setMinimumSize(QtCore.QSize(101, 171))
        self.gameBotton_2.setMaximumSize(QtCore.QSize(101, 171))
        self.gameBotton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gameBotton_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gameBotton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gameBotton_2.setStyleSheet("background-color: rgb(166, 166, 166);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../image/2048.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gameBotton_2.setIcon(icon1)
        self.gameBotton_2.setIconSize(QtCore.QSize(100, 150))
        self.gameBotton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.gameBotton_2.setObjectName("gameBotton_2")
        self.gridLayout.addWidget(self.gameBotton_2, 0, 1, 1, 1)
        self.gameBotton_1 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.gameBotton_1.setMinimumSize(QtCore.QSize(101, 171))
        self.gameBotton_1.setMaximumSize(QtCore.QSize(101, 171))
        self.gameBotton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gameBotton_1.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gameBotton_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gameBotton_1.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.gameBotton_1.setIcon(icon1)
        self.gameBotton_1.setIconSize(QtCore.QSize(100, 150))
        self.gameBotton_1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.gameBotton_1.setObjectName("gameBotton_1")
        self.gridLayout.addWidget(self.gameBotton_1, 0, 0, 1, 1)
        self.Game_Area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.Game_Area, 1, 0, 1, 2)
        self.Leaderboard_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Leaderboard_Area.setWidgetResizable(True)
        self.Leaderboard_Area.setObjectName("Leaderboard_Area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 671, 385))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Leaderboard_Area.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.Leaderboard_Area, 0, 1, 1, 1)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(350, 200))
        self.logo.setMaximumSize(QtCore.QSize(350, 200))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../image/游戏大logo.png"))
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 0, 1, 1)
        self.Game_Area.raise_()
        self.logo.raise_()
        self.Leaderboard_Area.raise_()
        UserMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserMainWindow)
        QtCore.QMetaObject.connectSlotsByName(UserMainWindow)

    def retranslateUi(self, UserMainWindow):
        _translate = QtCore.QCoreApplication.translate
        UserMainWindow.setWindowTitle(_translate("UserMainWindow", "Stepic"))
        self.gameBotton_2.setText(_translate("UserMainWindow", "2048"))
        self.gameBotton_1.setText(_translate("UserMainWindow", "2048"))
