# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests
import json
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserMainWindow(object):
    def setupUi(self, UserMainWindow):
        UserMainWindow.setObjectName("UserMainWindow")
        UserMainWindow.resize(1000, 750)
        UserMainWindow.setMinimumSize(QtCore.QSize(500, 500))
        UserMainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserMainWindow.setWindowIcon(icon)
        UserMainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(UserMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Leaderboard_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Leaderboard_Area.setWidgetResizable(True)
        self.Leaderboard_Area.setObjectName("Leaderboard_Area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Leaderboard_Area.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.Leaderboard_Area, 0, 1, 2, 2)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(350, 200))
        self.logo.setMaximumSize(QtCore.QSize(350, 200))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../image/游戏大logo.png"))
        self.logo.setObjectName("logo")
        self.gridLayout_2.addWidget(self.logo, 0, 0, 2, 1)
        self.Game_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Game_Area.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.Game_Area.setWidgetResizable(True)
        self.Game_Area.setObjectName("Game_Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")

        url = "http://106.13.236.185:5000/api/game/query_all_pub"
        r = requests.post(url=url, data="")
        games = json.loads(r.text)

        self.game_Button = []
        index = 0
        maxX = 10
        for game in games:
            game_Button = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
            game_Button.setMinimumSize(QtCore.QSize(101, 171))
            game_Button.setMaximumSize(QtCore.QSize(101, 171))
            game_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            game_Button.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
            game_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
            game_Button.setStyleSheet("background-color: rgb(166, 166, 166);")
            icon1 = QtGui.QIcon()
            icon1.addPixmap(QtGui.QPixmap("../image/game/" + game['image'].split('/')[-1]), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            game_Button.setIcon(icon1)
            game_Button.setIconSize(QtCore.QSize(100, 150))
            game_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
            game_Button.setObjectName("game_Button_" + str(game['gid']))
            self.game_Button.append(game_Button)
            self.gridLayout.addWidget(game_Button, index // maxX, index % maxX, 1, 1)

            index += 1


        self.Game_Area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.Game_Area, 2, 0, 1, 3)
        self.Game_Area.raise_()
        self.logo.raise_()
        self.Leaderboard_Area.raise_()

        UserMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserMainWindow)
        QtCore.QMetaObject.connectSlotsByName(UserMainWindow)

    def retranslateUi(self, UserMainWindow):
        _translate = QtCore.QCoreApplication.translate
        UserMainWindow.setWindowTitle(_translate("UserMainWindow", "Stepic"))
        url = "http://106.13.236.185:5000/api/game/query_all_pub"
        r = requests.post(url=url, data="")
        games = json.loads(r.text)
        index = 0
        for game in games:
            self.game_Button[index].setText(_translate("UserMainWindow", game['gname']))
            index += 1
